name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
      - name: Install deps
        run: composer install --no-interaction --no-progress
      - name: Lint (basic)
        run: php -l src/Lib/Logger.php
      - name: Tests
        run: vendor/bin/phpunit --configuration phpunit.xml || true # placeholder até definirmos tests reais
